name: github pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.131.0"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: snicoll/snicoll.github.io
          publish_dir: ./public
          user_name: snicoll
          user_email: stephane@nicoll.net
          publish_branch: main
          cname: snicoll.be
